version: '3.8'

services:
  # FreshNutrients Chat API
  chatbot-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
      - ENABLE_API_AUTH=true
      - ENABLE_RATE_LIMITING=true
      - ENABLE_HTTPS_REDIRECT=false
      # Database configuration (use environment variables)
      - AZURE_SQL_SERVER=${AZURE_SQL_SERVER}
      - AZURE_SQL_DATABASE=${AZURE_SQL_DATABASE}
      - AZURE_SQL_USERNAME=${AZURE_SQL_USERNAME}
      - AZURE_SQL_PASSWORD=${AZURE_SQL_PASSWORD}
      # Azure OpenAI configuration
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      # Security
      - API_SECRET_KEY=${API_SECRET_KEY}
      - ALLOWED_ORIGINS=http://localhost:3000,https://your-wix-site.com
    volumes:
      - ./app:/app/app  # Mount for development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - chatbot-network

  # Redis for production rate limiting (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge

volumes:
  redis-data:
