# Azure deployment configuration for FreshNutrients Chat API
# This file contains infrastructure as code for Azure Container Apps

apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshnutrients-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: freshnutrients-chatbot
  template:
    metadata:
      labels:
        app: freshnutrients-chatbot
    spec:
      containers:
      - name: chatbot-api
        image: freshnutrients/chatbot-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
        - name: ENABLE_API_AUTH
          value: "true"
        - name: ENABLE_RATE_LIMITING
          value: "true"
        - name: ENABLE_HTTPS_REDIRECT
          value: "true"
        - name: AZURE_SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: server
        - name: AZURE_SQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: database
        - name: AZURE_SQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: username
        - name: AZURE_SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: password
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: openai-secrets
              key: endpoint
        - name: AZURE_OPENAI_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secrets
              key: key
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: secret-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: freshnutrients-chatbot-service
spec:
  selector:
    app: freshnutrients-chatbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
